config/routes.rb
Rails.application.routes.draw do
  
  root  'pages#index'        #URLの指定がない時
  get 'pages/help'
  
  get 'topics/new'
  get 'sessions/new'
  
  resources :users
  resources :topics do
    resources :comments
  end
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get     '/login',  to: 'sessions#new'
  post    '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  
  
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  validates :user_id, presence: true
  validates :topic_id, presence: true
  
  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  
  # それぞれのtopicは１つのuserに所属している。１つなのでモデル名は単数形。
  # belongs_to,has_manyでインスタンスを作っている。
  # この１文でuserモデルの指定とuser_idという外部キーを指定している。
  # この書き方だとuserモデルを指定するというのがRailsで決まっている。
  belongs_to :user
  
  # Imageuploaderファイルとtopicモデルのimageカラムを紐付ける
  mount_uploader :image, ImageUploader
  
  has_many :favorites
  # favorite_usersはただの名前。Railsの作法から外れているのでsourceでモデルを指定している。
  # favoriteモデルに紐づいているuserモデルの中のカラムはuser_idしかないのでuser_idと紐付けられる。
  has_many :favorite_users, through: :favorites, source: 'user'
  # dependent: :destroy => topic削除されたらcommentsも削除される
  has_many :comments, dependent: :destroy
  has_many :comment_users, through: :comments, source: 'user'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15 }
  
  VARID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VARID_EMAIL_REGEX }
  
  VARID_PASSWORD_REGEX = /\A(?=.*[0-9])(?=.*[a-zA-Z])([a-zA-Z0-9]+)\z/
  # length: { in: 8..32 }の書き方もできる
  validates :password, presence: true, length: { minimum: 8, maximum: 32 }, format: { with: VARID_PASSWORD_REGEX } 
  
  
  has_secure_password
  
  # １つのUserは複数のtopicを持つ。has_manyの場合はRailsの命名規則で必ずモデル名を複数形にする。
  has_many :topics
  has_many :favorites
  # throughを使うことでログインしているユーザーがいいねしているtopicを全て取得できる。
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :comments
  has_many :comment_topics, through: :comments, source: 'topic'
end

app/controllers/application_controller.rb
# application_controllerはcontrollerで共通するコードを指定する
class ApplicationController < ActionController::Base
  
  # ハッカーからサイトを守るための記述
  protect_from_forgery with: :exception
  
  # フラッシュのキーとして使えるように登録
  add_flash_types :success, :info, :warning, :danger
 
  # helper_methodを記述することにより、application_helperでも以下のメソッドを使用可能にする。
  helper_method :current_user, :logged_in?
  
  def current_user
    # @current_user = @current_user || User.find_by(id: session[:user_id])
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @topic = Topic.find(params[:topic_id])
    @comment = Comment.new
  end
  
  def create
    @topic = Topic.find(params[:topic_id])
    # build => 親モデルに属する子モデルのインスタンスを生成したい場合に使うメソッド。
    # 外部キーに値が入った状態でインスタンスが生成できる。
    # buildはnewのaliasで、同じメソッドだけど、暗黙の了解でモデルの関連づけをした時に使う。
    @comment = @topic.comments.build(comment_params)
    # @comment = Comment.new(comment_params)
    # @comment.topic_id = params[:topic_id]
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to topics_path, success: 'コメントを投稿しました'
    else
      flash.now[:denger] = 'コメント投稿に失敗しました'
      render :new
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end
  
  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    
    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入りに登録に失敗しました'
    end
  end
  
  def destroy
    Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id]).destroy
    redirect_to topics_path, success: 'お気に入りを解除しました'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    # ストロングパラメータなしの記述
    # user = User.find_by(email: params[:session][:email])
    # if user && user.authenticate(params[:session][:password])
    
    # email_paramsの返り値は{email: params[:email]}なのでシンボルを指定しなくて良い。
    user = User.find_by(email_params)
    # password_paramsの返り値は{password: params[:password]}
    # authenticateにハッシュ化されていないパスワードの値を渡すと合っているか確認してくれるので、渡す際にはパスワードの値のみ渡したい。
    # password_params[:password]と指定することでパスワードの値のみ取り出せる。
    if user && user.authenticate(password_params[:password])
    # log_in(user)と同じ意味。別の書き方ができる。log_in メソッドに引数userを渡している。
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      # render action: :new の略。同じコントローラー内のnewアクションを表示させる。
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end
  
  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def email_params
    params.require(:session).permit(:email)
  end
  
  def password_params
    params.require(:session).permit(:password)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    # includesメソッドは指定したモデルのデータを一括で取得しキャッシュしておくことで
    # 「N＋1問題」を防ぐことができる。
    # 本当は配列を渡すのでincludes([:favorite_users, :comments])だけれど、省略して記述できる。
    @topics = Topic.all.includes(:favorite_users, :comments)
    # puts "aaa"
    # puts Topic.all.includes(:favorite_users, :comments).to_sql
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    # current_userに紐づくtopicsのインスタンスを生成
    # topicsはuserモデルのhas_manyで定義されている
    # topicsはリレーションだがメソッドのように使える。
    @topic = current_user.topics.new(topic_params)
    
    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end
  
  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    # @user = User.new(name: params[:user][:name], email: params[:user][:email]) 悪意あるユーザーが不正なデータを送信しても受け取ってしまうので変更。
    @user = User.new(user_params)
    if @user.save
      # flash[:success]="登録が完了しました"
      # redirect_to root_pathを１行で書いた記述。
      # noticeじゃなくsuccessを使うのはBootstrapで定義されているcssを用いるため。
      # BootstrapBootstrapで使えるのはsuccess,info,warning,dangerの４種類。
      redirect_to root_path, success: '登録が完了しました'
    else
      # redirect_toの時はflash,renderのときはflash.nowを使う。
      # flashは直後のリクエスト後に表示される。ルーティングに返すredirect_toの時には表示されるが、
      # ルーティングに返さず直接ビューを表示するrenderの時はflash.nowを使う。
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    # .requireメソッドがデータのオブジェクト名を定め、.permitメソッドで変更を加えられる（保存の処理ができる）キーを指定する。
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# application_helperなどのhelperはviewで使用する共通のコードを指定する
module ApplicationHelper
  
  # Dry(同じコードは繰り返し書かない)というRailsの設計理念に違反するために削除が必要。
  # application_controller内に記述した helper_method :current_user, :logged_in?　により削除が可能になる。
  
  # def current_user
  #   @current_user ||= User.find_by(id: session[:user_id])
  # end
  
  # def logged_in?
  #   !current_user.nil?
  # end
  
  
 
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="comments-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 comments-new-container">
        <h1 class="text-center">コメント投稿</h1>
          <%= form_for [@topic, @comment] do |f| %>
            <div class="form-group">
              <%= f.label :コメント %>
              <%= f.text_area :content %>
            </div>
            <%= f.submit "投稿する", class: "btn-block" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--alert-%= key %はalert-success、alert-dangerに読み変えられる。Bootstrapのalert-successのcssを適用させるため。-->
    <!--roleは役割。cssの記述。Webアクセシビリティ向上のために入力する。-->
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    
    <% end %>
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
        <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to favorites_index_path do %>
                <%= image_tag "icons/heart.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <%= image_tag "icons/camera.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
</script>
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make you Happy</h1>
    <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
    <p>heroku デプロイ作業用コメント</p>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign up', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white'%>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <!--image_tagはHTMLの<img>タグを生成するためのメソッド。-->
            <!--画像ファイルの配置場所は一般的に２箇所。-->
            <!--app/assets/images配下とpublic配下。-->
            <!--images配下の画像ファイルパスは以下のように記述。-->
            <!--public配下の画像を表示する場合は/から始める。-->
            <%= image_tag topic.image.url %>
            <!--include?はrailsのメソッド。存在しているか確認する時に使用する。-->
            <!--a = ["a","b","c"]の時-->
            <!--a.include?("b")  => true-->
            <!--a.include?("z")  => false-->
            <% if !topic.favorite_users.include?(current_user) %>
            <!--params[:topic_id]にtopic.idを入れる-->
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                <% image_tag 'icons/heart-pink.png', class: 'topic-index-icon topic-index-icon-red' %>
              <% end %>
            <% end %>
            <%= topic.favorite_users.count %>
            <%= link_to new_topic_comment_path(topic_id: topic.id) do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
            <h2>コメント</h2>
            <% topic.comments.each do |comment| %>
              <p><%= comment.content %></p>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <!--画像を送信する時はmultipart: trueが必要だったが、Rails4以降のform_forやform_withでは-->
        <!--フォーム内に関連づけられたfile_fieldがある場合は自動的にmultipart: trueが適用されるので記述の省略が可能。-->
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image %>
          </div>
          
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          
          <% if logged_in? %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class:'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form_group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
        
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>